version: '3.4'

services:
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=my-username
      - MONGO_INITDB_ROOT_PASSWORD=my-root-password
    volumes:
      - /data/db:/data/db
  authapi:
    image: authapi
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    links:
      - db
    volumes:
      - /app/node_modules
      - .:/app
      - /data/db:/data/db
    ports:
      - 3000:3000
    command: ['npm', 'run', 'dev']
  # db:
  #   image: 'mongo'
  #   container_name: MONGODB_MEDIUM
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - ./data/db:/data/db
