version: '3.4'

services:
  db:
    image: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - /data/db:/data/db
  authapi:
    image: authapi
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    links:
      - db
    volumes:
      - /app/node_modules
      - .:/app
      - /data/db:/data/db
    ports:
      - ${PORT}:3000
    command: ['npm', 'run', 'dev']
