version: '3.4'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT}:27017
  authapi:
    image: authapi
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - /app/node_modules
      - .:/app
      - /data/db:/data/db
    ports:
      - ${PORT}:3000
    command: ['npm', 'run', 'dev']
